version: '3'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container2
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=User
      - MYSQL_PASSWORD=123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  db_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
